global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'maheshkumar08042006@gmail.com'
  smtp_auth_username: 'maheshkumar08042006@gmail.com'
  smtp_auth_password: 'ggjiedzuxvxmnxqi'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'maheshkumarawsdevops@gmail.com'
    send_resolved: true
